# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_auto_20180107_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('enrolled_courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
