# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=254)),
            ],
        ),
    ]
